version: '3'
services:
  hw07-app-1:
    build: .
    ports:
      - "3000:3000"
  hw07-nginx-1:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hw07-app-1

